/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Bass: typeof import('./components/Bass.vue')['default']
    Bucket: (typeof import("./components/Bucket.vue"))["default"]
    Camera: typeof import('./components/Camera.vue')['default']
    FreeSound: typeof import('./components/FreeSound.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Microphone: typeof import('./components/Microphone.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    PianoKey: typeof import('./components/PianoKey.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sequencer: typeof import('./components/Sequencer.vue')['default']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    Sounds: typeof import('./components/Sounds.vue')['default']
    Tempo: typeof import('./components/Tempo.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}
